version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: daily
    assignees:
      - nxtlo
    rebase-strategy: auto
    target-branch: master

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    assignees:
      - nxtlo
    rebase-strategy: auto
    target-branch: master
