blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/nxtlo/aiobungie/discussions
    about: Please ask and answer questions about aiobungie on the github discussions.
